# Generated by Django 3.2 on 2021-04-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('iata_code', models.CharField(max_length=3, unique=True, verbose_name='Код аэропорта')),
                ('air_name', models.CharField(max_length=100, verbose_name='Имя аэропорта')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.city', verbose_name='Город')),
            ],
        ),
    ]
