# Generated by Django 3.2 on 2021-04-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'managed': False},
        ),
    ]
