# Generated by Django 3.2 on 2021-04-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_airport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('fly_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, verbose_name='Дата отправления')),
                ('arrival_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_to', to='tickets.airport', verbose_name='Куда')),
                ('takeoff_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_from', to='tickets.airport', verbose_name='Откуда')),
            ],
        ),
    ]
