# Generated by Django 3.2 on 2021-04-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_airport_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table='airports_table',
        ),
    ]
