# Generated by Django 3.2 on 2021-04-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Дата отправления')),
                ('arrival_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_to', to='tickets.airport', verbose_name='Куда')),
                ('takeoff_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_from', to='tickets.airport', verbose_name='Откуда')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bought', models.BooleanField()),
                ('t_class', models.CharField(choices=[('A', 'Первый класс'), ('C', 'Бизнес-класс'), ('X', 'Эконом')], default='A', max_length=35, verbose_name='Класс билета')),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flight', verbose_name='Номер рейса')),
            ],
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
    ]
