# Generated by Django 3.2 on 2021-04-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_airport_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table=None,
        ),
    ]
