# Generated by Django 3.2 on 2021-04-21 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210414_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название типа')),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 21, 10, 9, 55, 188211), verbose_name='Время прибытия'),
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='takeoff_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 21, 10, 9, 55, 188187), verbose_name='Время отправления'),
        ),
        migrations.CreateModel(
            name='AirTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flight', verbose_name='Назначенный вылет')),
            ],
        ),
    ]
