# Generated by Django 3.2 on 2021-04-21 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210421_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 21, 10, 11, 15, 956409), verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='takeoff_time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 21, 10, 11, 15, 956375), verbose_name='Время отправления'),
        ),
    ]
