# Generated by Django 3.2 on 2021-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20210421_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='takeoff_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправления'),
        ),
    ]
