# Generated by Django 3.2 on 2021-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20210421_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='patro',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='employee',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
