# Generated by Django 3.2 on 2021-04-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20210422_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flight', verbose_name='Назначенный вылет')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.employee', verbose_name='Рабочий')),
            ],
        ),
        migrations.DeleteModel(
            name='AirTeam',
        ),
    ]
