# Generated by Django 3.2 on 2021-04-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20210422_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя самолета')),
                ('pl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.planetype', verbose_name='Тип самолета')),
            ],
        ),
    ]
