# Generated by Django 3.2 on 2021-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20210422_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
