# Generated by Django 3.2 on 2021-04-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='name',
        ),
    ]
