# Generated by Django 3.2 on 2021-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_rename_position_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='en_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Международное название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
    ]
