# Generated by Django 3.2 on 2021-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20210422_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=35, null=True, verbose_name='Имя самолета'),
        ),
    ]
