# Generated by Django 3.2 on 2021-04-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_plane_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.plane', verbose_name='Самолет'),
        ),
    ]
