# Generated by Django 3.2 on 2021-04-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_flight_plane'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlineteam',
            options={'verbose_name': 'Экипаж', 'verbose_name_plural': 'Экипажи'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='plane',
            options={'verbose_name': 'Самолет', 'verbose_name_plural': 'Самолеты'},
        ),
        migrations.AlterModelOptions(
            name='planetype',
            options={'verbose_name': 'Тип самолета', 'verbose_name_plural': 'Типы самолетов'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
    ]
