# Generated by Django 3.2 on 2021-04-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20210427_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tickets_num',
            field=models.IntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(null=True, verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats_number',
            field=models.IntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='takeoff_time',
            field=models.DateTimeField(null=True, verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='planetype',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Название типа самолета'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=55, null=True, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_bought',
            field=models.BooleanField(verbose_name='Куплен ли билет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
