# Generated by Django 3.2 on 2021-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20210428_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='t_class',
            field=models.CharField(choices=[('A', 'Первый класс'), ('C', 'Бизнес-класс'), ('X', 'Эконом')], default='Первый класс', max_length=35, verbose_name='Класс билета'),
        ),
    ]
