# Generated by Django 3.2 on 2021-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_alter_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='t_class',
            field=models.CharField(choices=[('Первый класс', 'Первый класс'), ('Бизнес-класс', 'Бизнес-класс'), ('Эконом', 'Эконом')], default='Первый класс', max_length=35, verbose_name='Класс билета'),
        ),
    ]
